version: '3.8'

services:
  web:
    build: .
    container_name: saberhacer_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: saberhacer_db
    environment:
      MYSQL_ROOT_PASSWORD: ""          # contraseña vacía para root
      MYSQL_DATABASE: music_store_unidad3
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
